package com.senac.etapa3_pi.view;

import com.senac.etapa3_pi.view.cadastroConsultaView;
import com.senac.etapa3_pi.view.cadastroMedicoView;
import com.senac.etapa3_pi.view.cadastroPacienteView;
import dao.ConsultaDao;
import dao.MedicoDao;
import dao.PacienteDao;
import java.util.List;
import java.util.Optional;
import javax.swing.table.DefaultTableModel;
import model.Consulta;
import model.Medico;
import model.Paciente;

/**
 *
 * @author zanat
 */
public class listarConsultaView extends javax.swing.JFrame {

    /**
     * Creates new form listarConsultaView
     */
    public listarConsultaView() {
        initComponents();
      
    }
        
    ConsultaDao consultaDao = new ConsultaDao();
    PacienteDao pacienteDao = new PacienteDao();
    MedicoDao medicoDao = new MedicoDao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        cadastroPaciente = new javax.swing.JButton();
        cadastroConsulta = new javax.swing.JButton();
        cadastroMedico = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Perpetua", 3, 48)); // NOI18N
        jLabel1.setText("Gerenciador hospital");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Consultas");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua", 3, 48)); // NOI18N
        jLabel2.setText("Gerenciador hospital");

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Paciente", "Data consulta", "Diagnostico", "Duração", "Prescrição", "Medico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConsulta);

        cadastroPaciente.setText("Cadastrar Paciente");
        cadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPacienteActionPerformed(evt);
            }
        });

        cadastroConsulta.setText("Cadastrar Consulta");
        cadastroConsulta.setToolTipText("");
        cadastroConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroConsultaActionPerformed(evt);
            }
        });

        cadastroMedico.setText("Cadastrar Médico");
        cadastroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(cadastroMedico)
                        .addGap(84, 84, 84)
                        .addComponent(cadastroPaciente)
                        .addGap(76, 76, 76)
                        .addComponent(cadastroConsulta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroPaciente)
                    .addComponent(cadastroConsulta)
                    .addComponent(cadastroMedico))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPacienteActionPerformed
     cadastroPacienteView paciente = new cadastroPacienteView();
     paciente.setLocationRelativeTo(null); 
            paciente.setVisible(true);
        
    }//GEN-LAST:event_cadastroPacienteActionPerformed

    private void cadastroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMedicoActionPerformed
       cadastroMedicoView medico = new cadastroMedicoView();
       medico.setLocationRelativeTo(null); 
            medico.setVisible(true);
    }//GEN-LAST:event_cadastroMedicoActionPerformed

    private void cadastroConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroConsultaActionPerformed
     cadastroConsultaView consulta = new cadastroConsultaView();
     consulta.setLocationRelativeTo(null); 
            consulta.setVisible(true);
    }//GEN-LAST:event_cadastroConsultaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         preencheTabela(consultaDao.listar());
    }//GEN-LAST:event_formComponentShown

    
     private void preencheTabela(List<Consulta> consultas) {
        String columns[] = {"Paciente", "Data", "Diagnostico", "Duração", "Prescrição", "Medico"};
        String dados[][] = new String[consultas.size()][columns.length];

        int i = 0;
        for (Consulta c : consultas) {
            dados[i] = new String[]{                               
                
                
                
                String.valueOf(getNomePaciente(c.getIdPaciente())),
                String.valueOf(c.getDataConsulta()),
                c.getDiagnostico(),
                String.valueOf(c.getDuracao()),
                c.getPrescricao(),
                String.valueOf(getNomeMedico(c.getIdMedico()))};
            i++;
        }

        DefaultTableModel model = new DefaultTableModel(dados, columns);
        tbConsulta.setModel(model);
    }
     
     
     private String getNomePaciente(Long id){
         Optional<Paciente> p = pacienteDao.getById(id);
                
                if(p.isPresent()){
                    return (p.get().getNome());
                }
                
                return "";
         
     }
     
     private String getNomeMedico(Long id){
         Optional<Medico> m = medicoDao.getById(id);
                
                if(m.isPresent()){
                    return (m.get().getNome());
                }
         
                return "";
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroConsulta;
    private javax.swing.JButton cadastroMedico;
    private javax.swing.JButton cadastroPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsulta;
    // End of variables declaration//GEN-END:variables

}

